---
title: Mark Eschbach II
url: https://personallyabstract.org
baseurl: ""
permalink: pretty
collections:
  philosophy:
    output: true
    permalink: /philosophy-blog/:title
  projects:
    output: true
    permalink: /project-blog/:title
defaults:
  - scope:
      path: ""
      type: philosophy
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: default
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
---