# Site settings
title: Philosophy Blog
description: A blog exploring philosophical ideas and questions.
baseurl: "" # e.g., "/blog" if hosted in a subdirectory
url: "http://localhost:4000" # Replace with your site’s URL

# Build settings
markdown: kramdown
theme: minima # Optional; remove if not using a theme
plugins:
  - jekyll-feed

# Permalinks
permalink: /:year/:month/:day/:title/

# Post settings
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/