title: Philosophy Blog
description: A blog exploring philosophical ideas
baseurl: ""
url: "https://markopolo2023.github.io"
collections:
  philosophy:
    output: true
    permalink: /philosophy/:title
defaults:
  - scope:
      path: ""
      type: philosophy
    values:
      layout: post
plugins:
  - jekyll-feed